bot: #where the bots will send their messages
  status: 1234567890 #channel ids, leave one blank to send both status and data into one channel
  data: 0987654321  
  period: 30 #integer value in minutes of how often to scan, you can pick earlier but do note that openinsider-scraper doesn't appear to scrape anything of significant when timespans are low
  
filter:
  quantity: 20000 #the amount of stocks a trade detail must have before it is sent to the server
  date: 5 #the maximum date before the trade cannot be reported (when the trade was performed? the data in the csv is ambigious)

special: #values to measure a trade as special (yellow)
  quantity: 300000 
  date: 2
